/* eslint-disable no-console */
/**
 * Build script for BSPK UI
 *
 * This script compiles TypeScript files, processes CSS files, and prepares the final distribution package.
 *
 * It performs the following tasks:
 *
 * 1.
 *
 * Compiles TypeScript files using `tsc` and `tsc-alias`. 2. Processes SASS files using `npm run sass`. 3. Copies styles
 * from `@bspk/styles` to a temporary directory. 4. Creates importable CSS files for each @bspk/styles brand. 5. Creates
 * importable CSS files for each component. 6. Fixes import paths in JavaScript files. 7. Moves the temporary build
 * directory to the final distribution directory. 8. Updates the package exports to include component directories.
 *
 * $ npx tsx build.ts
 */
import child_process from 'child_process';
import fs_ from 'fs';
import path from 'path';
import util from 'util';

import packageData from './package.json';
import { BRANDS } from './src';

const exec = util.promisify(child_process.exec);
const writeFile = util.promisify(fs_.writeFile);
const readDir = util.promisify(fs_.readdir);
const readFile = (filePath: string) => util.promisify(fs_.readFile)(filePath, 'utf-8');

const STYLES_SOURCE_DIR = path.dirname(import.meta.resolve('@bspk/styles/package.json').split('file:')[1]);

const dist = path.resolve('./dist');
const tempStylesPath = path.resolve('./dist/styles');

const RESET = '\x1b[0m';
const GREEN = '\x1b[32m';
const BLUE = '\x1b[34m';

async function main() {
    const startTime = Date.now();

    console.log(`${BLUE}Building BSPK UI...${RESET}`);

    await exec(`rm -rf ${dist} && mkdir -p ${tempStylesPath}`);

    await exec('npm run tsc && npm run sass');

    // copy the styles from @bspk/styles to the temp styles directory
    await Promise.all(
        BRANDS.map(async ({ slug }) => {
            const brandStylesPath = path.resolve(STYLES_SOURCE_DIR, `${slug}.css`);
            await exec(`cp ${brandStylesPath} ${path.resolve(tempStylesPath, `${slug}.css`)}`);
        }),
    );

    await fileProcessing();

    await componentExports();

    // copy dist to dist

    const endTime = Date.now();

    console.log(`${GREEN}BSPK UI build completed successfully (${(endTime - startTime) / 1000}s)${RESET}`);
}

main();

async function fileProcessing() {
    const allFiles = await readDir(dist, { encoding: 'utf-8', recursive: true, withFileTypes: true });

    return Promise.all(
        allFiles.map(async (dirent) => {
            if (!dirent.isFile()) return;

            const filePath = path.resolve(dirent.parentPath, dirent.name);

            // make importable .css files
            if (filePath.endsWith('.css')) {
                await createImportableCss(await readFile(filePath), filePath.replace(/\.css$/, '.css.js'));
            }

            // fix import paths in .js files
            if (filePath.endsWith('.js')) {
                const newFileContent = (await readFile(filePath)).replace(
                    /import ['"]([^'"]+\/)?([^.]+)\.(s?css)['"];?/g,
                    (_match, importPath = '', name) => {
                        const nextImportPath = (importPath || '').replace('@bspk/styles/', '../../styles/');
                        return `import '${nextImportPath}${name}.css.js';`;
                    },
                );
                await writeFile(filePath, newFileContent, 'utf-8');
            }
        }),
    );
}

async function componentExports() {
    const nextExports = { ...packageData['static-exports'] };

    (await readDir(path.resolve('./dist/components'), { withFileTypes: true })).forEach((dirent) => {
        if (!dirent.isDirectory() || dirent.name.startsWith('.')) return;
        nextExports[`./${dirent.name}/*`] = `./dist/components/${dirent.name}/*.js`;
        nextExports[`./${dirent.name}`] = `./dist/components/${dirent.name}/index.js`;
    });

    (packageData.exports as Record<string, string>) = nextExports as Record<string, string>;
    return writeFile(path.resolve('./package.json'), `${JSON.stringify(packageData, null, 4)}\n`, 'utf-8');
}

async function createImportableCss(cssContent: string, destPath: string, id?: string) {
    return await writeFile(
        destPath,
        `/** * This file is generated by the build script.
* Do not edit this file directly. */
const style = document.createElement('style');
style.appendChild(document.createTextNode(\`${cssContent}\`));
document.head.appendChild(style);
${id ? `\ndocument.querySelector('#${id}')?.remove(); style.id = '${id}';` : ''}
`,
    );
}
