/* eslint-disable no-console */
import { execSync as execSyncBase } from 'child_process';
import fs from 'fs';
import path from 'path';

import packageData from './package.json';
import { BRANDS } from './src';

const execSync = (command: string) => execSyncBase(command, { stdio: 'inherit' });

const STYLES_SOURCE_DIR = path.dirname(import.meta.resolve('@bspk/styles/package.json').split('file:')[1]);

const arg = process.argv[2];

(() => {
    console.log('⚡️\t Building BSPK UI');
    generateDist();
    copyBrandStyles();
    fileProcessing();
    componentExports();
})();

function generateDist() {
    if (arg === 'force') execSync('rm -rf ./dist');

    if (fs.existsSync('./dist')) {
        console.log('⚡️\t /dist directory already exists, skipping build');
        process.exit(0);
    }

    execSync('mkdir -p ./dist');
    execSync('tsc && tsc-alias');
    execSync('npm run sass');
    execSync('mkdir -p ./dist/styles');
}

function copyBrandStyles() {
    BRANDS.forEach(({ slug }) => {
        const brandStylesPath = path.resolve(STYLES_SOURCE_DIR, `${slug}.css`);
        execSync(`cp ${brandStylesPath} ./dist/styles/${slug}.css`);
        createImportableCss(brandStylesPath, path.resolve('./dist/styles/', `${slug}.css.js`));
    });
}

function fileProcessing() {
    fs.readdirSync('./dist', { encoding: 'utf-8', recursive: true, withFileTypes: true }).forEach((dirent) => {
        if (!dirent.isFile()) return;

        const fileName = dirent.name;
        const filePath = path.resolve(dirent.parentPath, fileName);
        let fileContent = fs.readFileSync(filePath, 'utf-8');

        // create importable css files
        if (dirent.name.endsWith('.css')) {
            const destPath = path.join(dirent.parentPath, dirent.name.replace('.css', '.css.js'));
            createImportableCss(fileContent, destPath);
            return;
        }

        if (dirent.name.endsWith('.js')) {
            // fix css and scss imports, including @bspk/styles imports
            const cssImportMatches = [...fileContent.matchAll(/import '(.*\/)([^.]+).[s]*css';/g)];
            fileContent = cssImportMatches.reduce((nextContent, [full, importPath, name]) => {
                // this only works for jsj in the components directory
                const nextImportPath = importPath.replace('@bspk/styles/', '../../styles/');
                return nextContent.replace(full, `import '${nextImportPath}${name}.css.js';`);
            }, fileContent);

            fs.writeFileSync(filePath, fileContent, 'utf-8');
        }
    });
}

function componentExports() {
    const nextExports = { ...packageData['non-component-exports'] };

    fs.readdirSync(path.resolve('./dist/components'), { withFileTypes: true }).forEach((dirent) => {
        if (!dirent.isDirectory() || dirent.name.startsWith('.')) return;

        nextExports[`./${dirent.name}/*`] = `./dist/components/${dirent.name}/*.js`;
        nextExports[`./${dirent.name}`] = `./dist/components/${dirent.name}/index.js`;
    });

    (packageData.exports as Record<string, string>) = nextExports as Record<string, string>;
    fs.writeFileSync(path.resolve('./package.json'), JSON.stringify(packageData, null, 4), 'utf-8');
}

function createImportableCss(cssContent: string, destPath: string, id?: string) {
    fs.writeFileSync(
        destPath,
        `/** * This file is generated by the build script.
* Do not edit this file directly. */
const style = document.createElement('style');
style.appendChild(document.createTextNode(\`${cssContent.trim()}\`));
document.head.appendChild(style);
${id ? `\ndocument.querySelector('#${id}')?.remove(); style.id = '${id}';` : ''}
`,
    );
}
