/* eslint-disable @cspell/spellchecker */
import { IconName } from '@bspk/icons/meta';
import { CountryCode } from 'libphonenumber-js';

export type SupportedCountryCode = keyof CountryCodeData;

type CountryCodeData = Omit<
    Record<CountryCode, { name: string; flagIconName: IconName; code: CountryCode }>,
    | 'AC'
    | 'CI'
    | 'CV'
    | 'FM'
    | 'GP'
    | 'KN'
    | 'LC'
    | 'MF'
    | 'NC'
    | 'RE'
    | 'SH'
    | 'SJ'
    | 'TA'
    | 'VA'
    | 'VC'
    | 'WF'
    | 'XK'
    | 'YT'
>;

export const COUNTRY_CODE_DATA: CountryCodeData = {
    AD: { name: 'Andorra', flagIconName: 'FlagAndorra', code: 'AD' },
    AE: { name: 'United Arab Emirates', flagIconName: 'FlagUnitedArabEmirates', code: 'AE' },
    AF: { name: 'Afghanistan', flagIconName: 'FlagAfghanistan', code: 'AF' },
    AG: { name: 'Antigua and Barbuda', flagIconName: 'FlagAntiguaAndBarbuda', code: 'AG' },
    AI: { name: 'Anguilla', flagIconName: 'FlagAnguilla', code: 'AI' },
    AL: { name: 'Albania', flagIconName: 'FlagAlbania', code: 'AL' },
    AM: { name: 'Armenia', flagIconName: 'FlagArmenia', code: 'AM' },
    AO: { name: 'Angola', flagIconName: 'FlagAngola', code: 'AO' },
    AR: { name: 'Argentina', flagIconName: 'FlagArgentina', code: 'AR' },
    AS: { name: 'American Samoa', flagIconName: 'FlagAmericanSamoa', code: 'AS' },
    AT: { name: 'Austria', flagIconName: 'FlagAustria', code: 'AT' },
    AU: { name: 'Australia', flagIconName: 'FlagAustralia', code: 'AU' },
    AW: { name: 'Aruba', flagIconName: 'FlagAruba', code: 'AW' },
    AX: { name: 'Åland Islands', flagIconName: 'FlagAlandIsland', code: 'AX' },
    AZ: { name: 'Azerbaijan', flagIconName: 'FlagAzerbaijan', code: 'AZ' },
    BA: { name: 'Bosnia and Herzegovina', flagIconName: 'FlagBosniaAndHerzegovina', code: 'BA' },
    BB: { name: 'Barbados', flagIconName: 'FlagBarbados', code: 'BB' },
    BD: { name: 'Bangladesh', flagIconName: 'FlagBangladesh', code: 'BD' },
    BE: { name: 'Belgium', flagIconName: 'FlagBelgium', code: 'BE' },
    BF: { name: 'Burkina Faso', flagIconName: 'FlagBurkinaFaso', code: 'BF' },
    BG: { name: 'Bulgaria', flagIconName: 'FlagBulgaria', code: 'BG' },
    BH: { name: 'Bahrain', flagIconName: 'FlagBahrain', code: 'BH' },
    BI: { name: 'Burundi', flagIconName: 'FlagBurundi', code: 'BI' },
    BJ: { name: 'Benin', flagIconName: 'FlagBenin', code: 'BJ' },
    BL: { name: 'Saint Barthélemy', flagIconName: 'FlagSaintBarthelemy', code: 'BL' },
    BM: { name: 'Bermuda', flagIconName: 'FlagBermuda', code: 'BM' },
    BN: { name: 'Brunei', flagIconName: 'FlagBrunei', code: 'BN' },
    BO: { name: 'Bolivia', flagIconName: 'FlagBolivia', code: 'BO' },
    BQ: { name: 'Bonaire, Sint Eustatius and Saba', flagIconName: 'FlagBonaire', code: 'BQ' },
    BR: { name: 'Brazil', flagIconName: 'FlagBrazil', code: 'BR' },
    BS: { name: 'Bahamas', flagIconName: 'FlagBahamas', code: 'BS' },
    BT: { name: 'Bhutan', flagIconName: 'FlagBhutan', code: 'BT' },
    BW: { name: 'Botswana', flagIconName: 'FlagBotswana', code: 'BW' },
    BY: { name: 'Belarus', flagIconName: 'FlagBelarus', code: 'BY' },
    BZ: { name: 'Belize', flagIconName: 'FlagBelize', code: 'BZ' },
    CA: { name: 'Canada', flagIconName: 'FlagCanada', code: 'CA' },
    CC: { name: 'Cocos (Keeling) Islands', flagIconName: 'FlagCocosIslands', code: 'CC' },
    CD: { name: 'Democratic Republic of the Congo', flagIconName: 'FlagDemocraticRepublicOfTheCongo', code: 'CD' },
    CF: { name: 'Central African Republic', flagIconName: 'FlagCentralAfricanRepublic', code: 'CF' },
    CG: { name: 'Republic of the Congo', flagIconName: 'FlagRepublicOfTheCongo', code: 'CG' },
    CH: { name: 'Switzerland', flagIconName: 'FlagSwitzerland', code: 'CH' },
    CK: { name: 'Cook Islands', flagIconName: 'FlagCookIsland', code: 'CK' },
    CL: { name: 'Chile', flagIconName: 'FlagChile', code: 'CL' },
    CM: { name: 'Cameroon', flagIconName: 'FlagCameroon', code: 'CM' },
    CN: { name: 'China', flagIconName: 'FlagChina', code: 'CN' },
    CO: { name: 'Colombia', flagIconName: 'FlagColombia', code: 'CO' },
    CR: { name: 'Costa Rica', flagIconName: 'FlagCostaRica', code: 'CR' },
    CU: { name: 'Cuba', flagIconName: 'FlagCuba', code: 'CU' },
    CW: { name: 'Curaçao', flagIconName: 'FlagCuracao', code: 'CW' },
    CX: { name: 'Christmas Island', flagIconName: 'FlagChristmasIsland', code: 'CX' },
    CY: { name: 'Cyprus', flagIconName: 'FlagCyprus', code: 'CY' },
    CZ: { name: 'Czech Republic', flagIconName: 'FlagCzechRepublic', code: 'CZ' },
    DE: { name: 'Germany', flagIconName: 'FlagGermany', code: 'DE' },
    DJ: { name: 'Djibouti', flagIconName: 'FlagDjibouti', code: 'DJ' },
    DK: { name: 'Denmark', flagIconName: 'FlagDenmark', code: 'DK' },
    DM: { name: 'Dominica', flagIconName: 'FlagDominica', code: 'DM' },
    DO: { name: 'Dominican Republic', flagIconName: 'FlagDominicanRepublic', code: 'DO' },
    DZ: { name: 'Algeria', flagIconName: 'FlagAlgeria', code: 'DZ' },
    EC: { name: 'Ecuador', flagIconName: 'FlagEcuador', code: 'EC' },
    EE: { name: 'Estonia', flagIconName: 'FlagEstonia', code: 'EE' },
    EG: { name: 'Egypt', flagIconName: 'FlagEgypt', code: 'EG' },
    EH: { name: 'Western Sahara', flagIconName: 'FlagWestSahara', code: 'EH' },
    ER: { name: 'Eritrea', flagIconName: 'FlagEritrea', code: 'ER' },
    ES: { name: 'Spain', flagIconName: 'FlagSpain', code: 'ES' },
    ET: { name: 'Ethiopia', flagIconName: 'FlagEthiopia', code: 'ET' },
    FI: { name: 'Finland', flagIconName: 'FlagFinland', code: 'FI' },
    FJ: { name: 'Fiji', flagIconName: 'FlagFiji', code: 'FJ' },
    FK: { name: 'Falkland Islands', flagIconName: 'FlagFalklandIslands', code: 'FK' },
    FO: { name: 'Faroe Islands', flagIconName: 'FlagFaroeIslands', code: 'FO' },
    FR: { name: 'France', flagIconName: 'FlagFrance', code: 'FR' },
    GA: { name: 'Gabon', flagIconName: 'FlagGabon', code: 'GA' },
    GB: { name: 'United Kingdom', flagIconName: 'FlagUnitedKingdom', code: 'GB' },
    GD: { name: 'Grenada', flagIconName: 'FlagGrenada', code: 'GD' },
    GE: { name: 'Georgia', flagIconName: 'FlagGeorgia', code: 'GE' },
    GF: { name: 'French Guiana', flagIconName: 'FlagFrenchGuiana', code: 'GF' },
    GG: { name: 'Guernsey', flagIconName: 'FlagGuernsey', code: 'GG' },
    GH: { name: 'Ghana', flagIconName: 'FlagGhana', code: 'GH' },
    GI: { name: 'Gibraltar', flagIconName: 'FlagGibraltar', code: 'GI' },
    GL: { name: 'Greenland', flagIconName: 'FlagGreeland', code: 'GL' },
    GM: { name: 'Gambia', flagIconName: 'FlagGambia', code: 'GM' },
    GN: { name: 'Guinea', flagIconName: 'FlagGuinea', code: 'GN' },
    GQ: { name: 'Equatorial Guinea', flagIconName: 'FlagEquatorialGuinea', code: 'GQ' },
    GR: { name: 'Greece', flagIconName: 'FlagGreece', code: 'GR' },
    GT: { name: 'Guatemala', flagIconName: 'FlagGuatemala', code: 'GT' },
    GU: { name: 'Guam', flagIconName: 'FlagGuam', code: 'GU' },
    GW: { name: 'Guinea-Bissau', flagIconName: 'FlagGuinea', code: 'GW' },
    GY: { name: 'Guyana', flagIconName: 'FlagGuyana', code: 'GY' },
    HK: { name: 'Hong Kong', flagIconName: 'FlagHongKong', code: 'HK' },
    HN: { name: 'Honduras', flagIconName: 'FlagHonduras', code: 'HN' },
    HR: { name: 'Croatia', flagIconName: 'FlagCroatia', code: 'HR' },
    HT: { name: 'Haiti', flagIconName: 'FlagHaiti', code: 'HT' },
    HU: { name: 'Hungary', flagIconName: 'FlagHungary', code: 'HU' },
    ID: { name: 'Indonesia', flagIconName: 'FlagIndonesia', code: 'ID' },
    IE: { name: 'Ireland', flagIconName: 'FlagIreland', code: 'IE' },
    IL: { name: 'Israel', flagIconName: 'FlagIsrael', code: 'IL' },
    IM: { name: 'Isle of Man', flagIconName: 'FlagIsleOfMan', code: 'IM' },
    IN: { name: 'India', flagIconName: 'FlagIndia', code: 'IN' },
    IO: { name: 'British Indian Ocean Territory', flagIconName: 'FlagIndianOceanTerritory', code: 'IO' },
    IQ: { name: 'Iraq', flagIconName: 'FlagIraq', code: 'IQ' },
    IR: { name: 'Iran', flagIconName: 'FlagIran', code: 'IR' },
    IS: { name: 'Iceland', flagIconName: 'FlagIceland', code: 'IS' },
    IT: { name: 'Italy', flagIconName: 'FlagItaly', code: 'IT' },
    JE: { name: 'Jersey', flagIconName: 'FlagJersey', code: 'JE' },
    JM: { name: 'Jamaica', flagIconName: 'FlagJamaica', code: 'JM' },
    JO: { name: 'Jordan', flagIconName: 'FlagJordan', code: 'JO' },
    JP: { name: 'Japan', flagIconName: 'FlagJapan', code: 'JP' },
    KE: { name: 'Kenya', flagIconName: 'FlagKenya', code: 'KE' },
    KG: { name: 'Kyrgyzstan', flagIconName: 'FlagKyrgyzstan', code: 'KG' },
    KH: { name: 'Cambodia', flagIconName: 'FlagCambodia', code: 'KH' },
    KI: { name: 'Kiribati', flagIconName: 'FlagKiribati', code: 'KI' },
    KM: { name: 'Comoros', flagIconName: 'FlagComoros', code: 'KM' },
    KP: { name: 'North Korea', flagIconName: 'FlagNorthKorea', code: 'KP' },
    KR: { name: 'South Korea', flagIconName: 'FlagSouthKorea', code: 'KR' },
    KW: { name: 'Kuwait', flagIconName: 'FlagKuwait', code: 'KW' },
    KY: { name: 'Cayman Islands', flagIconName: 'FlagCaymanIslands', code: 'KY' },
    KZ: { name: 'Kazakhstan', flagIconName: 'FlagKazakhstan', code: 'KZ' },
    LA: { name: 'Laos', flagIconName: 'FlagLaos', code: 'LA' },
    LB: { name: 'Lebanon', flagIconName: 'FlagLebanon', code: 'LB' },
    LI: { name: 'Liechtenstein', flagIconName: 'FlagLiechtenstein', code: 'LI' },
    LK: { name: 'Sri Lanka', flagIconName: 'FlagSriLanka', code: 'LK' },
    LR: { name: 'Liberia', flagIconName: 'FlagLiberia', code: 'LR' },
    LS: { name: 'Lesotho', flagIconName: 'FlagLesotho', code: 'LS' },
    LT: { name: 'Lithuania', flagIconName: 'FlagLithuania', code: 'LT' },
    LU: { name: 'Luxembourg', flagIconName: 'FlagLuxembourg', code: 'LU' },
    LV: { name: 'Latvia', flagIconName: 'FlagLatvia', code: 'LV' },
    LY: { name: 'Libya', flagIconName: 'FlagLibya', code: 'LY' },
    MA: { name: 'Morocco', flagIconName: 'FlagMorroco', code: 'MA' },
    MC: { name: 'Monaco', flagIconName: 'FlagMonaco', code: 'MC' },
    MD: { name: 'Moldova', flagIconName: 'FlagMoldova', code: 'MD' },
    ME: { name: 'Montenegro', flagIconName: 'FlagMontenegro', code: 'ME' },
    MG: { name: 'Madagascar', flagIconName: 'FlagMadagascar', code: 'MG' },
    MH: { name: 'Marshall Islands', flagIconName: 'FlagMarshallIslands', code: 'MH' },
    MK: { name: 'North Macedonia', flagIconName: 'FlagNorthMacedonia', code: 'MK' },
    ML: { name: 'Mali', flagIconName: 'FlagMali', code: 'ML' },
    MM: { name: 'Myanmar', flagIconName: 'FlagMyanmar', code: 'MM' },
    MN: { name: 'Mongolia', flagIconName: 'FlagMongolia', code: 'MN' },
    MO: { name: 'Macau', flagIconName: 'FlagMacau', code: 'MO' },
    MP: { name: 'Northern Mariana Islands', flagIconName: 'FlagNorthernMarianaIslands', code: 'MP' },
    MQ: { name: 'Martinique', flagIconName: 'FlagMartinique', code: 'MQ' },
    MR: { name: 'Mauritania', flagIconName: 'FlagMauritania', code: 'MR' },
    MS: { name: 'Montserrat', flagIconName: 'FlagMontserrat', code: 'MS' },
    MT: { name: 'Malta', flagIconName: 'FlagMalta', code: 'MT' },
    MU: { name: 'Mauritius', flagIconName: 'FlagMauritius', code: 'MU' },
    MV: { name: 'Maldives', flagIconName: 'FlagMaldives', code: 'MV' },
    MW: { name: 'Malawi', flagIconName: 'FlagMalawi', code: 'MW' },
    MX: { name: 'Mexico', flagIconName: 'FlagMexico', code: 'MX' },
    MY: { name: 'Malaysia', flagIconName: 'FlagMalasia', code: 'MY' },
    MZ: { name: 'Mozambique', flagIconName: 'FlagMozambique', code: 'MZ' },
    NA: { name: 'Namibia', flagIconName: 'FlagNamibia', code: 'NA' },
    NE: { name: 'Niger', flagIconName: 'FlagNiger', code: 'NE' },
    NF: { name: 'Norfolk Island', flagIconName: 'FlagNorfolkIsland', code: 'NF' },
    NG: { name: 'Nigeria', flagIconName: 'FlagNigeria', code: 'NG' },
    NI: { name: 'Nicaragua', flagIconName: 'FlagNicaragua', code: 'NI' },
    NL: { name: 'Netherlands', flagIconName: 'FlagNetherlands', code: 'NL' },
    NO: { name: 'Norway', flagIconName: 'FlagNorway', code: 'NO' },
    NP: { name: 'Nepal', flagIconName: 'FlagNepal', code: 'NP' },
    NR: { name: 'Nauru', flagIconName: 'FlagNauru', code: 'NR' },
    NU: { name: 'Niue', flagIconName: 'FlagNiue', code: 'NU' },
    NZ: { name: 'New Zealand', flagIconName: 'FlagNewZealand', code: 'NZ' },
    OM: { name: 'Oman', flagIconName: 'FlagOman', code: 'OM' },
    PS: { name: 'Palestine', flagIconName: 'FlagPalestine', code: 'PS' },
    PA: { name: 'Panama', flagIconName: 'FlagPanama', code: 'PA' },
    PE: { name: 'Peru', flagIconName: 'FlagPeru', code: 'PE' },
    PF: { name: 'French Polynesia', flagIconName: 'FlagFrenchPolynesia', code: 'PF' },
    PG: { name: 'Papua New Guinea', flagIconName: 'FlagPapuaNewGuinea', code: 'PG' },
    PH: { name: 'Philippines', flagIconName: 'FlagPhilippines', code: 'PH' },
    PK: { name: 'Pakistan', flagIconName: 'FlagPakistan', code: 'PK' },
    PL: { name: 'Poland', flagIconName: 'FlagPoland', code: 'PL' },
    PM: { name: 'Saint Pierre and Miquelon', flagIconName: 'FlagSaintBarthelemy', code: 'PM' },
    PR: { name: 'Puerto Rico', flagIconName: 'FlagPuertoRico', code: 'PR' },
    PT: { name: 'Portugal', flagIconName: 'FlagPortugal', code: 'PT' },
    PW: { name: 'Palau', flagIconName: 'FlagPalau', code: 'PW' },
    PY: { name: 'Paraguay', flagIconName: 'FlagParaguay', code: 'PY' },
    QA: { name: 'Qatar', flagIconName: 'FlagQatar', code: 'QA' },
    RO: { name: 'Romania', flagIconName: 'FlagRomania', code: 'RO' },
    RS: { name: 'Serbia', flagIconName: 'FlagSerbia', code: 'RS' },
    RU: { name: 'Russia', flagIconName: 'FlagRussia', code: 'RU' },
    RW: { name: 'Rwanda', flagIconName: 'FlagRwanda', code: 'RW' },
    SA: { name: 'Saudi Arabia', flagIconName: 'FlagSaudiArabia', code: 'SA' },
    SB: { name: 'Solomon Islands', flagIconName: 'FlagSolomonIslands', code: 'SB' },
    SC: { name: 'Seychelles', flagIconName: 'FlagSeychelles', code: 'SC' },
    SD: { name: 'Sudan', flagIconName: 'FlagSudan', code: 'SD' },
    SE: { name: 'Sweden', flagIconName: 'FlagSweden', code: 'SE' },
    SG: { name: 'Singapore', flagIconName: 'FlagSingapore', code: 'SG' },
    SI: { name: 'Slovenia', flagIconName: 'FlagSlovenia', code: 'SI' },
    SK: { name: 'Slovakia', flagIconName: 'FlagSlovakia', code: 'SK' },
    SL: { name: 'Sierra Leone', flagIconName: 'FlagSierraLeone', code: 'SL' },
    SM: { name: 'San Marino', flagIconName: 'FlagSanMarino', code: 'SM' },
    SN: { name: 'Senegal', flagIconName: 'FlagSenegal', code: 'SN' },
    SO: { name: 'Somalia', flagIconName: 'FlagSomalia', code: 'SO' },
    SR: { name: 'Suriname', flagIconName: 'FlagSuriname', code: 'SR' },
    SS: { name: 'South Sudan', flagIconName: 'FlagSouthSudan', code: 'SS' },
    ST: { name: 'São Tomé and Príncipe', flagIconName: 'FlagSaoTomeAndPrincipe', code: 'ST' },
    SV: { name: 'El Salvador', flagIconName: 'FlagElSalvador', code: 'SV' },
    SX: { name: 'Sint Maarten', flagIconName: 'FlagSintMaarten', code: 'SX' },
    SY: { name: 'Syria', flagIconName: 'FlagSyria', code: 'SY' },
    SZ: { name: 'Eswatini', flagIconName: 'FlagEswatini', code: 'SZ' },
    TC: { name: 'Turks and Caicos Islands', flagIconName: 'FlagTurksAndCaicos', code: 'TC' },
    TD: { name: 'Chad', flagIconName: 'FlagChad', code: 'TD' },
    TG: { name: 'Togo', flagIconName: 'FlagTogo', code: 'TG' },
    TH: { name: 'Thailand', flagIconName: 'FlagThailand', code: 'TH' },
    TJ: { name: 'Tajikistan', flagIconName: 'FlagTajikistan', code: 'TJ' },
    TK: { name: 'Tokelau', flagIconName: 'FlagTokelau', code: 'TK' },
    TL: { name: 'Timor-Leste', flagIconName: 'FlagTimorLeste', code: 'TL' },
    TM: { name: 'Turkmenistan', flagIconName: 'FlagTurkmenistan', code: 'TM' },
    TN: { name: 'Tunisia', flagIconName: 'FlagTunisia', code: 'TN' },
    TO: { name: 'Tonga', flagIconName: 'FlagTonga', code: 'TO' },
    TR: { name: 'Turkey', flagIconName: 'FlagTurkey', code: 'TR' },
    TT: { name: 'Trinidad and Tobago', flagIconName: 'FlagTrinidadAndTobago', code: 'TT' },
    TV: { name: 'Tuvalu', flagIconName: 'FlagTuvalu', code: 'TV' },
    TW: { name: 'Taiwan', flagIconName: 'FlagTaiwan', code: 'TW' },
    TZ: { name: 'Tanzania', flagIconName: 'FlagTanzania', code: 'TZ' },
    UA: { name: 'Ukraine', flagIconName: 'FlagUkraine', code: 'UA' },
    UG: { name: 'Uganda', flagIconName: 'FlagUganda', code: 'UG' },
    US: { name: 'United States of America', flagIconName: 'FlagUnitedStates', code: 'US' },
    UY: { name: 'Uruguay', flagIconName: 'FlagUruguay', code: 'UY' },
    UZ: { name: 'Uzbekistan', flagIconName: 'FlagUzbekistan', code: 'UZ' },
    VE: { name: 'Venezuela', flagIconName: 'FlagVenezuela', code: 'VE' },
    VG: { name: 'British Virgin Islands', flagIconName: 'FlagVirginIslandsBritish', code: 'VG' },
    VI: { name: 'United States Virgin Islands', flagIconName: 'FlagVirginIslands', code: 'VI' },
    VN: { name: 'Vietnam', flagIconName: 'FlagVietnam', code: 'VN' },
    VU: { name: 'Vanuatu', flagIconName: 'FlagVanuatu', code: 'VU' },
    WS: { name: 'Samoa', flagIconName: 'FlagSamoa', code: 'WS' },
    YE: { name: 'Yemen', flagIconName: 'FlagYemen', code: 'YE' },
    ZA: { name: 'South Africa', flagIconName: 'FlagSouthAfrica', code: 'ZA' },
    ZM: { name: 'Zambia', flagIconName: 'FlagZambia', code: 'ZM' },
    ZW: { name: 'Zimbabwe', flagIconName: 'FlagZimbabwe', code: 'ZW' },
} as const;

export const countryCodes = Object.keys(COUNTRY_CODE_DATA) as SupportedCountryCode[];
