/* eslint-disable @cspell/spellchecker */
import { IconName } from '@bspk/icons/meta';
import { CountryCode } from 'libphonenumber-js';

export type SupportedCountryCode = keyof CountryCodeData;

type CountryCodeData = Omit<
    Record<CountryCode, { name: string; flagIconName: IconName }>,
    | 'AC'
    | 'CI'
    | 'CV'
    | 'FM'
    | 'GP'
    | 'KN'
    | 'LC'
    | 'MF'
    | 'NC'
    | 'RE'
    | 'SH'
    | 'SJ'
    | 'TA'
    | 'VA'
    | 'VC'
    | 'WF'
    | 'XK'
    | 'YT'
>;

export const countryCodeData: CountryCodeData = {
    AD: { name: 'Andorra', flagIconName: 'FlagAndorra' },
    AE: { name: 'United Arab Emirates', flagIconName: 'FlagUnitedArabEmirates' },
    AF: { name: 'Afghanistan', flagIconName: 'FlagAfghanistan' },
    AG: { name: 'Antigua and Barbuda', flagIconName: 'FlagAntiguaAndBarbuda' },
    AI: { name: 'Anguilla', flagIconName: 'FlagAnguilla' },
    AL: { name: 'Albania', flagIconName: 'FlagAlbania' },
    AM: { name: 'Armenia', flagIconName: 'FlagArmenia' },
    AO: { name: 'Angola', flagIconName: 'FlagAngola' },
    AR: { name: 'Argentina', flagIconName: 'FlagArgentina' },
    AS: { name: 'American Samoa', flagIconName: 'FlagAmericanSamoa' },
    AT: { name: 'Austria', flagIconName: 'FlagAustria' },
    AU: { name: 'Australia', flagIconName: 'FlagAustralia' },
    AW: { name: 'Aruba', flagIconName: 'FlagAruba' },
    AX: { name: 'Åland Islands', flagIconName: 'FlagAlandIsland' },
    AZ: { name: 'Azerbaijan', flagIconName: 'FlagAzerbaijan' },
    BA: { name: 'Bosnia and Herzegovina', flagIconName: 'FlagBosniaAndHerzegovina' },
    BB: { name: 'Barbados', flagIconName: 'FlagBarbados' },
    BD: { name: 'Bangladesh', flagIconName: 'FlagBangladesh' },
    BE: { name: 'Belgium', flagIconName: 'FlagBelgium' },
    BF: { name: 'Burkina Faso', flagIconName: 'FlagBurkinaFaso' },
    BG: { name: 'Bulgaria', flagIconName: 'FlagBulgaria' },
    BH: { name: 'Bahrain', flagIconName: 'FlagBahrain' },
    BI: { name: 'Burundi', flagIconName: 'FlagBurundi' },
    BJ: { name: 'Benin', flagIconName: 'FlagBenin' },
    BL: { name: 'Saint Barthélemy', flagIconName: 'FlagSaintBarthelemy' },
    BM: { name: 'Bermuda', flagIconName: 'FlagBermuda' },
    BN: { name: 'Brunei', flagIconName: 'FlagBrunei' },
    BO: { name: 'Bolivia', flagIconName: 'FlagBolivia' },
    BQ: { name: 'Bonaire, Sint Eustatius and Saba', flagIconName: 'FlagBonaire' },
    BR: { name: 'Brazil', flagIconName: 'FlagBrazil' },
    BS: { name: 'Bahamas', flagIconName: 'FlagBahamas' },
    BT: { name: 'Bhutan', flagIconName: 'FlagBhutan' },
    BW: { name: 'Botswana', flagIconName: 'FlagBotswana' },
    BY: { name: 'Belarus', flagIconName: 'FlagBelarus' },
    BZ: { name: 'Belize', flagIconName: 'FlagBelize' },
    CA: { name: 'Canada', flagIconName: 'FlagCanada' },
    CC: { name: 'Cocos (Keeling) Islands', flagIconName: 'FlagCocosIslands' },
    CD: { name: 'Democratic Republic of the Congo', flagIconName: 'FlagDemocraticRepublicOfTheCongo' },
    CF: { name: 'Central African Republic', flagIconName: 'FlagCentralAfricanRepublic' },
    CG: { name: 'Republic of the Congo', flagIconName: 'FlagRepublicOfTheCongo' },
    CH: { name: 'Switzerland', flagIconName: 'FlagSwitzerland' },
    // CI: { //     name: "Ivory Coast", //     flagIconName: "FlagIvoryCoast"// },
    CK: { name: 'Cook Islands', flagIconName: 'FlagCookIsland' },
    CL: { name: 'Chile', flagIconName: 'FlagChile' },
    CM: { name: 'Cameroon', flagIconName: 'FlagCameroon' },
    CN: { name: 'China', flagIconName: 'FlagChina' },
    CO: { name: 'Colombia', flagIconName: 'FlagColombia' },
    CR: { name: 'Costa Rica', flagIconName: 'FlagCostaRica' },
    CU: { name: 'Cuba', flagIconName: 'FlagCuba' },
    // CV: { //     name: "Cape Verde", //     flagIconName: "FlagCapeVerde"// },
    CW: { name: 'Curaçao', flagIconName: 'FlagCuracao' },
    CX: { name: 'Christmas Island', flagIconName: 'FlagChristmasIsland' },
    CY: { name: 'Cyprus', flagIconName: 'FlagCyprus' },
    CZ: { name: 'Czech Republic', flagIconName: 'FlagCzechRepublic' },
    DE: { name: 'Germany', flagIconName: 'FlagGermany' },
    DJ: { name: 'Djibouti', flagIconName: 'FlagDjibouti' },
    DK: { name: 'Denmark', flagIconName: 'FlagDenmark' },
    DM: { name: 'Dominica', flagIconName: 'FlagDominica' },
    DO: { name: 'Dominican Republic', flagIconName: 'FlagDominicanRepublic' },
    DZ: { name: 'Algeria', flagIconName: 'FlagAlgeria' },
    EC: { name: 'Ecuador', flagIconName: 'FlagEcuador' },
    EE: { name: 'Estonia', flagIconName: 'FlagEstonia' },
    EG: { name: 'Egypt', flagIconName: 'FlagEgypt' },
    EH: { name: 'Western Sahara', flagIconName: 'FlagWestSahara' },
    ER: { name: 'Eritrea', flagIconName: 'FlagEritrea' },
    ES: { name: 'Spain', flagIconName: 'FlagSpain' },
    ET: { name: 'Ethiopia', flagIconName: 'FlagEthiopia' },
    FI: { name: 'Finland', flagIconName: 'FlagFinland' },
    FJ: { name: 'Fiji', flagIconName: 'FlagFiji' },
    FK: { name: 'Falkland Islands', flagIconName: 'FlagFalklandIslands' },
    // FM: { //     name: "Micronesia", //     flagIconName: "FlagMicronesia"// },
    FO: { name: 'Faroe Islands', flagIconName: 'FlagFaroeIslands' },
    FR: { name: 'France', flagIconName: 'FlagFrance' },
    GA: { name: 'Gabon', flagIconName: 'FlagGabon' },
    GB: { name: 'United Kingdom', flagIconName: 'FlagUnitedKingdom' },
    GD: { name: 'Grenada', flagIconName: 'FlagGrenada' },
    GE: { name: 'Georgia', flagIconName: 'FlagGeorgia' },
    GF: { name: 'French Guiana', flagIconName: 'FlagFrenchGuiana' },
    GG: { name: 'Guernsey', flagIconName: 'FlagGuernsey' },
    GH: { name: 'Ghana', flagIconName: 'FlagGhana' },
    GI: { name: 'Gibraltar', flagIconName: 'FlagGibraltar' },
    GL: { name: 'Greenland', flagIconName: 'FlagGreeland' },
    GM: { name: 'Gambia', flagIconName: 'FlagGambia' },
    GN: { name: 'Guinea', flagIconName: 'FlagGuinea' },
    // GP: { //     name: "Guadeloupe", //     flagIconName: "FlagGuadeloupe"// },
    GQ: { name: 'Equatorial Guinea', flagIconName: 'FlagEquatorialGuinea' },
    GR: { name: 'Greece', flagIconName: 'FlagGreece' },
    GT: { name: 'Guatemala', flagIconName: 'FlagGuatemala' },
    GU: { name: 'Guam', flagIconName: 'FlagGuam' },
    GW: { name: 'Guinea-Bissau', flagIconName: 'FlagGuinea' },
    GY: { name: 'Guyana', flagIconName: 'FlagGuyana' },
    HK: { name: 'Hong Kong', flagIconName: 'FlagHongKong' },
    HN: { name: 'Honduras', flagIconName: 'FlagHonduras' },
    HR: { name: 'Croatia', flagIconName: 'FlagCroatia' },
    HT: { name: 'Haiti', flagIconName: 'FlagHaiti' },
    HU: { name: 'Hungary', flagIconName: 'FlagHungary' },
    ID: { name: 'Indonesia', flagIconName: 'FlagIndonesia' },
    IE: { name: 'Ireland', flagIconName: 'FlagIreland' },
    IL: { name: 'Israel', flagIconName: 'FlagIsrael' },
    IM: { name: 'Isle of Man', flagIconName: 'FlagIsleOfMan' },
    IN: { name: 'India', flagIconName: 'FlagIndia' },
    IO: { name: 'British Indian Ocean Territory', flagIconName: 'FlagIndianOceanTerritory' },
    IQ: { name: 'Iraq', flagIconName: 'FlagIraq' },
    IR: { name: 'Iran', flagIconName: 'FlagIran' },
    IS: { name: 'Iceland', flagIconName: 'FlagIceland' },
    IT: { name: 'Italy', flagIconName: 'FlagItaly' },
    JE: { name: 'Jersey', flagIconName: 'FlagJersey' },
    JM: { name: 'Jamaica', flagIconName: 'FlagJamaica' },
    JO: { name: 'Jordan', flagIconName: 'FlagJordan' },
    JP: { name: 'Japan', flagIconName: 'FlagJapan' },
    KE: { name: 'Kenya', flagIconName: 'FlagKenya' },
    KG: { name: 'Kyrgyzstan', flagIconName: 'FlagKyrgyzstan' },
    KH: { name: 'Cambodia', flagIconName: 'FlagCambodia' },
    KI: { name: 'Kiribati', flagIconName: 'FlagKiribati' },
    KM: { name: 'Comoros', flagIconName: 'FlagComoros' },
    // KN: { //     name: "Saint Kitts and Nevis", //     flagIconName: "FlagSaintKittsandNevis"// },
    KP: { name: 'North Korea', flagIconName: 'FlagNorthKorea' },
    KR: { name: 'South Korea', flagIconName: 'FlagSouthKorea' },
    KW: { name: 'Kuwait', flagIconName: 'FlagKuwait' },
    KY: { name: 'Cayman Islands', flagIconName: 'FlagCaymanIslands' },
    KZ: { name: 'Kazakhstan', flagIconName: 'FlagKazakhstan' },
    LA: { name: 'Laos', flagIconName: 'FlagLaos' },
    LB: { name: 'Lebanon', flagIconName: 'FlagLebanon' },
    // LC: { //     name: "Saint Lucia", //     flagIconName: "FlagSaintLucia"// },
    LI: { name: 'Liechtenstein', flagIconName: 'FlagLiechtenstein' },
    LK: { name: 'Sri Lanka', flagIconName: 'FlagSriLanka' },
    LR: { name: 'Liberia', flagIconName: 'FlagLiberia' },
    LS: { name: 'Lesotho', flagIconName: 'FlagLesotho' },
    LT: { name: 'Lithuania', flagIconName: 'FlagLithuania' },
    LU: { name: 'Luxembourg', flagIconName: 'FlagLuxembourg' },
    LV: { name: 'Latvia', flagIconName: 'FlagLatvia' },
    LY: { name: 'Libya', flagIconName: 'FlagLibya' },
    MA: { name: 'Morocco', flagIconName: 'FlagMorroco' },
    MC: { name: 'Monaco', flagIconName: 'FlagMonaco' },
    MD: { name: 'Moldova', flagIconName: 'FlagMoldova' },
    ME: { name: 'Montenegro', flagIconName: 'FlagMontenegro' },
    // MF: { //     name: "Saint Martin", //     flagIconName: "FlagSaintMartin"// },
    MG: { name: 'Madagascar', flagIconName: 'FlagMadagascar' },
    MH: { name: 'Marshall Islands', flagIconName: 'FlagMarshallIslands' },
    MK: { name: 'North Macedonia', flagIconName: 'FlagNorthMacedonia' },
    ML: { name: 'Mali', flagIconName: 'FlagMali' },
    MM: { name: 'Myanmar', flagIconName: 'FlagMyanmar' },
    MN: { name: 'Mongolia', flagIconName: 'FlagMongolia' },
    MO: { name: 'Macau', flagIconName: 'FlagMacau' },
    MP: { name: 'Northern Mariana Islands', flagIconName: 'FlagNorthernMarianaIslands' },
    MQ: { name: 'Martinique', flagIconName: 'FlagMartinique' },
    MR: { name: 'Mauritania', flagIconName: 'FlagMauritania' },
    MS: { name: 'Montserrat', flagIconName: 'FlagMontserrat' },
    MT: { name: 'Malta', flagIconName: 'FlagMalta' },
    MU: { name: 'Mauritius', flagIconName: 'FlagMauritius' },
    MV: { name: 'Maldives', flagIconName: 'FlagMaldives' },
    MW: { name: 'Malawi', flagIconName: 'FlagMalawi' },
    MX: { name: 'Mexico', flagIconName: 'FlagMexico' },
    MY: { name: 'Malaysia', flagIconName: 'FlagMalasia' },
    MZ: { name: 'Mozambique', flagIconName: 'FlagMozambique' },
    NA: { name: 'Namibia', flagIconName: 'FlagNamibia' },
    // NC: { //     name: "New Caledonia", //     flagIconName: "FlagNewCaledonia"// },
    NE: { name: 'Niger', flagIconName: 'FlagNiger' },
    NF: { name: 'Norfolk Island', flagIconName: 'FlagNorfolkIsland' },
    NG: { name: 'Nigeria', flagIconName: 'FlagNigeria' },
    NI: { name: 'Nicaragua', flagIconName: 'FlagNicaragua' },
    NL: { name: 'Netherlands', flagIconName: 'FlagNetherlands' },
    NO: { name: 'Norway', flagIconName: 'FlagNorway' },
    NP: { name: 'Nepal', flagIconName: 'FlagNepal' },
    NR: { name: 'Nauru', flagIconName: 'FlagNauru' },
    NU: { name: 'Niue', flagIconName: 'FlagNiue' },
    NZ: { name: 'New Zealand', flagIconName: 'FlagNewZealand' },
    OM: { name: 'Oman', flagIconName: 'FlagOman' },
    PS: { name: 'Palestine', flagIconName: 'FlagPalestine' },
    PA: { name: 'Panama', flagIconName: 'FlagPanama' },
    PE: { name: 'Peru', flagIconName: 'FlagPeru' },
    PF: { name: 'French Polynesia', flagIconName: 'FlagFrenchPolynesia' },
    PG: { name: 'Papua New Guinea', flagIconName: 'FlagPapuaNewGuinea' },
    PH: { name: 'Philippines', flagIconName: 'FlagPhilippines' },
    PK: { name: 'Pakistan', flagIconName: 'FlagPakistan' },
    PL: { name: 'Poland', flagIconName: 'FlagPoland' },
    PM: { name: 'Saint Pierre and Miquelon', flagIconName: 'FlagSaintBarthelemy' },
    PR: { name: 'Puerto Rico', flagIconName: 'FlagPuertoRico' },
    PT: { name: 'Portugal', flagIconName: 'FlagPortugal' },
    PW: { name: 'Palau', flagIconName: 'FlagPalau' },
    PY: { name: 'Paraguay', flagIconName: 'FlagParaguay' },
    QA: { name: 'Qatar', flagIconName: 'FlagQatar' },
    // RE: { //     name: "Réunion", //     flagIconName: "FlagRéunion"// },
    RO: { name: 'Romania', flagIconName: 'FlagRomania' },
    RS: { name: 'Serbia', flagIconName: 'FlagSerbia' },
    RU: { name: 'Russia', flagIconName: 'FlagRussia' },
    RW: { name: 'Rwanda', flagIconName: 'FlagRwanda' },
    SA: { name: 'Saudi Arabia', flagIconName: 'FlagSaudiArabia' },
    SB: { name: 'Solomon Islands', flagIconName: 'FlagSolomonIslands' },
    SC: { name: 'Seychelles', flagIconName: 'FlagSeychelles' },
    SD: { name: 'Sudan', flagIconName: 'FlagSudan' },
    SE: { name: 'Sweden', flagIconName: 'FlagSweden' },
    SG: { name: 'Singapore', flagIconName: 'FlagSingapore' },
    // SH: { //     name: "Saint Helena", //     flagIconName: "FlagSaintHelena"// },
    SI: { name: 'Slovenia', flagIconName: 'FlagSlovenia' },
    // SJ: { //     name: "Svalbard and Jan Mayen", //     flagIconName: "FlagSvalbardandJanMayen"// },
    SK: { name: 'Slovakia', flagIconName: 'FlagSlovakia' },
    SL: { name: 'Sierra Leone', flagIconName: 'FlagSierraLeone' },
    SM: { name: 'San Marino', flagIconName: 'FlagSanMarino' },
    SN: { name: 'Senegal', flagIconName: 'FlagSenegal' },
    SO: { name: 'Somalia', flagIconName: 'FlagSomalia' },
    SR: { name: 'Suriname', flagIconName: 'FlagSuriname' },
    SS: { name: 'South Sudan', flagIconName: 'FlagSouthSudan' },
    ST: { name: 'São Tomé and Príncipe', flagIconName: 'FlagSaoTomeAndPrincipe' },
    SV: { name: 'El Salvador', flagIconName: 'FlagElSalvador' },
    SX: { name: 'Sint Maarten', flagIconName: 'FlagSintMaarten' },
    SY: { name: 'Syria', flagIconName: 'FlagSyria' },
    SZ: { name: 'Eswatini', flagIconName: 'FlagEswatini' },
    // TA: { //     name: "Tristan da Cunha", //     flagIconName: "FlagTristanDaCunha"// },
    TC: { name: 'Turks and Caicos Islands', flagIconName: 'FlagTurksAndCaicos' },
    TD: { name: 'Chad', flagIconName: 'FlagChad' },
    TG: { name: 'Togo', flagIconName: 'FlagTogo' },
    TH: { name: 'Thailand', flagIconName: 'FlagThailand' },
    TJ: { name: 'Tajikistan', flagIconName: 'FlagTajikistan' },
    TK: { name: 'Tokelau', flagIconName: 'FlagTokelau' },
    TL: { name: 'Timor-Leste', flagIconName: 'FlagTimorLeste' },
    TM: { name: 'Turkmenistan', flagIconName: 'FlagTurkmenistan' },
    TN: { name: 'Tunisia', flagIconName: 'FlagTunisia' },
    TO: { name: 'Tonga', flagIconName: 'FlagTonga' },
    TR: { name: 'Turkey', flagIconName: 'FlagTurkey' },
    TT: { name: 'Trinidad and Tobago', flagIconName: 'FlagTrinidadAndTobago' },
    TV: { name: 'Tuvalu', flagIconName: 'FlagTuvalu' },
    TW: { name: 'Taiwan', flagIconName: 'FlagTaiwan' },
    TZ: { name: 'Tanzania', flagIconName: 'FlagTanzania' },
    UA: { name: 'Ukraine', flagIconName: 'FlagUkraine' },
    UG: { name: 'Uganda', flagIconName: 'FlagUganda' },
    US: { name: 'United States of America', flagIconName: 'FlagUnitedStates' },
    UY: { name: 'Uruguay', flagIconName: 'FlagUruguay' },
    UZ: { name: 'Uzbekistan', flagIconName: 'FlagUzbekistan' },
    // VA: { //     name: "Vatican City", //     flagIconName: "FlagVaticanCity"// },
    // VC: { //     name: "Saint Vincent and the Grenadines", //     flagIconName: "FlagSaintVincentandtheGrenadines"// },
    VE: { name: 'Venezuela', flagIconName: 'FlagVenezuela' },
    VG: { name: 'British Virgin Islands', flagIconName: 'FlagVirginIslandsBritish' },
    VI: { name: 'United States Virgin Islands', flagIconName: 'FlagVirginIslands' },
    VN: { name: 'Vietnam', flagIconName: 'FlagVietnam' },
    VU: { name: 'Vanuatu', flagIconName: 'FlagVanuatu' },
    // WF: { //     name: "Wallis and Futuna", //     flagIconName: "FlagWallisandFutuna"// },
    WS: { name: 'Samoa', flagIconName: 'FlagSamoa' },
    // XK: { //     name: "Kosovo", //     flagIconName: "FlagKosovo"// },
    YE: { name: 'Yemen', flagIconName: 'FlagYemen' },
    // YT: { //     name: "Mayotte", //     flagIconName: "FlagMayotte"// },
    ZA: { name: 'South Africa', flagIconName: 'FlagSouthAfrica' },
    ZM: { name: 'Zambia', flagIconName: 'FlagZambia' },
    ZW: { name: 'Zimbabwe', flagIconName: 'FlagZimbabwe' },
} as const;

export const countryCodes = Object.keys(countryCodeData) as SupportedCountryCode[];
