/* eslint-disable no-console */
/**
 * $ npm run build:css
 *
 * Generates the `TxtVariants.ts` and `colorVariants.ts` file from the `anywhere.css` file.
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

import './utils.js';

// reference only - import '@bspk/styles/anywhere.css';

const anywhereCssFile = path.resolve(__dirname, '../node_modules/@bspk/styles/anywhere.css');

const fileContent = (content: string) => `/**
 * This file is generated by the build-css script.
 * Do not edit this file directly.
 * Instead, edit the script and run it again. */ 
${content}

/** Copyright 2025 Anywhere Real Estate - CC BY 4.0 */
`;

function generateFileLinted(filePath: string, content: string) {
    fs.writeFileSync(filePath, fileContent(content));

    execSync(`eslint --fix ${filePath} && npx prettier --write ${filePath}`, {
        stdio: 'inherit',
    });

    console.info(`\n${filePath} generated`);
}

function generateTxtVariants(variables: Record<string, string>) {
    const txtVariables = Object.entries(variables)
        // text variable values start with weight value
        .filter(([, value]) => /^\d{3}\s/.test(value));

    const variants = new Set<string>();

    txtVariables.forEach(([variable]) => {
        const variant = variable
            .substring(2)
            .replace(/^desktop-/, '')
            .replace(/^mobile-/, '');

        variants.add(variant);
    });

    generateFileLinted(
        path.resolve(__dirname, '../src/utils/txtVariants.ts'),
        [
            `export const TXT_VARIANTS = ${JSON.stringify([...variants])} as const;`,
            `export type TxtVariant = typeof TXT_VARIANTS[number];`,
        ].join('\n'),
    );
}

function generateColorVariants(variables: Record<string, string>) {
    const surfaceVariables = Object.keys(variables).filter((variable) => variable.includes('surface-spectrum'));
    const foregroundVariables = Object.keys(variables).filter((variable) => variable.includes('foreground-spectrum'));

    const manualVariants = {
        grey: {
            foreground: '--foreground-neutral-on-surface-variant-01',
            surface: '--surface-neutral-t2-lowest',
        },
        white: {
            foreground: '--foreground-neutral-on-surface-variant-01',
            surface: '--surface-neutral-t1-base',
        },
        primary: {
            foreground: '--foreground-brand-primary-depth',
            surface: '--surface-brand-primary-highlight',
        },
        secondary: {
            foreground: '--foreground-brand-secondary-depth',
            surface: '--surface-brand-secondary-highlight',
        },
    };

    const manualVariantErrors: string[] = Object.entries(manualVariants)
        .flatMap(([variant, { foreground, surface }]) =>
            [
                !variables[foreground] ? `Missing foreground variable for ${variant}` : [],
                !variables[surface] ? `Missing surface variable for ${variant}` : [],
            ].flat(),
        )
        .filter(Boolean);

    if (manualVariantErrors.length) {
        console.error(manualVariantErrors.join('\n'));
        process.exit(1);
    }

    const foundVariants: Record<string, unknown> = Object.fromEntries(
        surfaceVariables.map((surfaceVariable) => {
            const variant = surfaceVariable.replace('--surface-spectrum-', '');
            const foregroundVariable = foregroundVariables.find((variable) => variable.endsWith(variant));

            return [
                variant,
                {
                    foreground: foregroundVariable,
                    surface: surfaceVariable,
                },
            ];
        }),
    );

    const variants = { ...manualVariants, ...foundVariants };

    generateFileLinted(
        'src/utils/colorVariants.ts',
        [
            `export const COLOR_VARIANTS = ${JSON.stringify(Object.keys(variants))} as const;`,
            `export type ColorVariant = typeof COLOR_VARIANTS[number];`,
        ].join('\n'),
    );

    const cssFilePath = path.resolve(__dirname, '../src/colors.scss');

    fs.writeFileSync(
        cssFilePath,
        fileContent(
            Object.entries(variants)
                .map(
                    ([variant, { foreground, surface }]) => `
        [data-color='${variant}'] {
            --foreground: var(${foreground});
            --background: var(${surface});
        }
    `,
                )
                .join('\n'),
        ),
    );

    execSync(
        //
        `npx prettier --write '${cssFilePath}' && npx stylelint '${cssFilePath}' --fix`,
        { stdio: 'inherit' },
    );
}

function main() {
    const variableMatches = fs.readFileSync(anywhereCssFile, 'utf8').matchAll(/(--[^:]+):\s*([^\n;]+)/g);
    const variables = Object.fromEntries([...variableMatches].map((match) => [match[1], match[2]]));

    generateTxtVariants(variables);

    generateColorVariants(variables);
}

main();

/** Copyright 2025 Anywhere Real Estate - CC BY 4.0 */
