/* eslint-disable no-console */
/**
 * - Updates the @bspk/styles package,
 * - Regenerates the `TxtVariants.ts`, `colorVariants.ts`, and `colors.scss` files,
 * - Ensures that variables used in components still exist in the updated @bspk/styles package.
 *
 * $ npx tsx .scripts/update-css.ts
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { getCssVariables, getStylesRoot, prettyLint, reportMissingVariables } from './utils';
import { Brand } from 'src/types/common';

function main() {
    const variables = getCssVariables();

    execSync(`npm un @bspk/styles && npm i @bspk/styles@latest`, { stdio: 'inherit' });

    copyStylesLibraryCss();

    generateTxtVariants(variables);

    generateColorVariants(variables);

    reportMissingVariables(variables);
}

main();

function copyStylesLibraryCss() {
    const providerDemoPath = path.resolve(__dirname, '../src/components/StylesProviderDemo');

    // Example CSS copy
    fs.writeFileSync(
        path.resolve(providerDemoPath, 'exampleCss.ts'),
        `export const EXAMPLE_CSS: Record<'example', string> = {
    example: \`${fs.readFileSync(path.resolve(__dirname, '../src/styles/example.css'), 'utf-8')}\`,
};
`,
    );

    const BrandsCss: Partial<Record<Brand, string>> = {};

    fs.readdirSync(getStylesRoot(), 'utf8').forEach((file) => {
        if (!file.endsWith('.css')) return;
        BrandsCss[file.replace('.css', '') as Brand] = fs.readFileSync(path.resolve(getStylesRoot(), file), 'utf-8');
    });

    fs.writeFileSync(
        path.resolve(providerDemoPath, 'brandsCss.ts'),
        `/* eslint-disable @cspell/spellchecker */\nimport { Brand } from '-/types/common';

        export const BRANDS_CSS: Record<Brand, string> = ${JSON.stringify(BrandsCss, null, 4)};
`,
    );

    execSync(`npx prettier --write '${path.resolve(providerDemoPath, 'brandsCss.ts')}'`, {
        stdio: 'inherit',
    });
}

function fileContent(content: string) {
    return `/**
 * This file is generated by the update-css script.
 * Do not edit this file directly.
 * Instead, edit the script and run it again. */ 
${content}

/** Copyright 2026 Anywhere Real Estate - CC BY 4.0 */
`;
}

function generateFileLinted(filePath: string, content: string) {
    fs.writeFileSync(filePath, fileContent(content));
    prettyLint(filePath);
    console.info(`\n${filePath} generated`);
}

function generateTxtVariants(variables: Record<string, string>) {
    const txtVariables = Object.entries(variables)
        // text variable values start with weight value
        .filter(([, value]) => /^\d{3}\s/.test(value));

    const variants = new Set<string>();

    txtVariables.forEach(([variable]) => {
        const variant = variable
            .substring(2)
            .replace(/^desktop-/, '')
            .replace(/^mobile-/, '');

        variants.add(variant);
    });

    generateFileLinted(
        path.resolve(__dirname, '../src/utils/txtVariants.ts'),
        [
            `export const TXT_VARIANTS = ${JSON.stringify([...variants])} as const;`,
            `export type TxtVariant = typeof TXT_VARIANTS[number];`,
        ].join('\n'),
    );
}

function generateColorVariants(variables: Record<string, string>) {
    const surfaceVariables = Object.keys(variables).filter((variable) => variable.includes('surface-spectrum'));
    const foregroundVariables = Object.keys(variables).filter((variable) => variable.includes('foreground-spectrum'));

    const manualVariants: Record<string, Record<string, `--${string}`>> = {
        grey: {
            foreground: '--foreground-neutral-on-surface-variant-01',
            surface: '--surface-neutral-t2-lowest',
        },
        white: {
            foreground: '--foreground-neutral-on-surface-variant-01',
            surface: '--surface-neutral-t1-base',
        },
        primary: {
            foreground: '--foreground-brand-primary-depth',
            surface: '--surface-brand-primary-highlight',
        },
        secondary: {
            foreground: '--foreground-brand-secondary-depth',
            surface: '--surface-brand-secondary-highlight',
        },
    };

    const manualVariantErrors: string[] = Object.entries(manualVariants)
        .flatMap(([variant, { foreground, surface }]) =>
            [
                !variables[foreground] ? `Missing foreground variable for ${variant}` : [],
                !variables[surface] ? `Missing surface variable for ${variant}` : [],
            ].flat(),
        )
        .filter(Boolean);

    if (manualVariantErrors.length) {
        console.error(manualVariantErrors.join('\n'));
        process.exit(1);
    }

    const foundVariants: Record<string, Record<string, `--${string}` | undefined>> = Object.fromEntries(
        surfaceVariables.map((surfaceVariable) => {
            const variant = surfaceVariable.replace('--surface-spectrum-', '');
            const foregroundVariable = foregroundVariables.find((variable) => variable.endsWith(variant));

            return [
                variant,
                {
                    foreground: foregroundVariable as `--${string}` | undefined,
                    surface: surfaceVariable as `--${string}` | undefined,
                },
            ];
        }),
    );

    const variants = { ...manualVariants, ...foundVariants };

    generateFileLinted(
        './src/utils/colorVariants.ts',
        [
            `export const COLOR_VARIANTS = ${JSON.stringify(Object.keys(variants))} as const;`,
            `export type ColorVariant = typeof COLOR_VARIANTS[number];`,
        ].join('\n'),
    );

    const cssFilePath = path.resolve(__dirname, '../src/styles/colors.scss');

    fs.writeFileSync(
        cssFilePath,
        fileContent(
            Object.entries(variants)
                .map(
                    ([variant, { foreground, surface }]) => `
        [data-color='${variant}'] {
            --foreground: var(${foreground});
            --background: var(${surface});
        }
    `,
                )
                .join('\n'),
        ),
    );

    execSync(
        //
        `npx prettier --write '${cssFilePath}' && npx stylelint '${cssFilePath}' --fix`,
        { stdio: 'inherit' },
    );
}

/** Copyright 2026 Anywhere Real Estate - CC BY 4.0 */
